import { DataSource } from 'typeorm';
import {
  Brand,
  Store,
  User,
  Role,
  Permission,
  Member,
  Coach,
  Course,
  CourseSchedule,
  MembershipCard,
  GroupClassCard,
  PersonalTrainingCard,
  CheckIn,
  Booking,
} from './entities';

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DATABASE_HOST || 'localhost',
  port: parseInt(process.env.DATABASE_PORT || '5432', 10),
  username: process.env.DATABASE_USERNAME || 'gym_user',
  password: process.env.DATABASE_PASSWORD || 'dev_password_123',
  database: process.env.DATABASE_NAME || 'gym_saas_dev',
  entities: [
    Brand,
    Store,
    User,
    Role,
    Permission,
    Member,
    Coach,
    Course,
    CourseSchedule,
    MembershipCard,
    GroupClassCard,
    PersonalTrainingCard,
    CheckIn,
    Booking,
  ],
  migrations: [__dirname + '/migrations/*{.ts,.js}'],
  synchronize: false,
  logging: process.env.NODE_ENV === 'development',
});
